#!/usr/bin/env bash
# Zero-manual-config release signing (§44).
#
# Sourced/executed by every Android builder *before* Gradle runs. It:
#   1. Restores the project's keystore from KEYSTORE_BASE64 (sealed in the
#      platform vault and injected per build), or
#   2. Generates a fresh RSA-2048 keystore with `keytool` on the very first
#      build (UPLOAD_* passwords come from the vault too), and POSTs it back to
#      the API so every later build signs with the SAME key, and
#   3. Writes gradle.properties entries + a `signing.gradle` snippet the app's
#      build.gradle can `apply from:` — without touching the user's source.
#
# Required env (injected by the platform):  UPLOAD_STORE_PASSWORD, UPLOAD_KEY_PASSWORD,
#   UPLOAD_KEY_ALIAS, UPLOAD_KEY_DNAME, UPLOAD_KEYSTORE_PATH
# Optional: KEYSTORE_BASE64, APK_FACTORY_API, APK_FACTORY_PROJECT_ID
set -euo pipefail

ANDROID_DIR="${1:-android}"
KS_PATH="${UPLOAD_KEYSTORE_PATH:-release.keystore}"
ALIAS="${UPLOAD_KEY_ALIAS:-apkfactory}"
DNAME="${UPLOAD_KEY_DNAME:-CN=app, OU=Cloud APK Factory, O=apkfactory, C=US}"

if [ -z "${UPLOAD_STORE_PASSWORD:-}" ] || [ -z "${UPLOAD_KEY_PASSWORD:-}" ]; then
  echo ">> [sign] no signing credentials injected — building unsigned/debug"
  exit 0
fi

mkdir -p "$ANDROID_DIR/app"
KS_ABS="$ANDROID_DIR/app/$KS_PATH"

if [ -n "${KEYSTORE_BASE64:-}" ]; then
  echo ">> [sign] restoring project keystore from vault"
  printf '%s' "$KEYSTORE_BASE64" | base64 -d > "$KS_ABS"
else
  echo ">> [sign] first build — generating keystore ($ALIAS)"
  keytool -genkeypair -v -keystore "$KS_ABS" -alias "$ALIAS" -keyalg RSA -keysize 2048 -validity 10000 \
    -dname "$DNAME" -storepass "$UPLOAD_STORE_PASSWORD" -keypass "$UPLOAD_KEY_PASSWORD" >/dev/null 2>&1
  CERT_SHA=$(keytool -list -v -keystore "$KS_ABS" -alias "$ALIAS" -storepass "$UPLOAD_STORE_PASSWORD" 2>/dev/null | awk '/SHA256:/{print $2; exit}')
  if [ -n "${APK_FACTORY_API:-}" ] && [ -n "${APK_FACTORY_PROJECT_ID:-}" ]; then
    echo ">> [sign] sealing keystore in platform vault (cert $CERT_SHA)"
    B64=$(base64 -w0 "$KS_ABS" 2>/dev/null || base64 "$KS_ABS" | tr -d '\n')
    curl -fsS -X POST "$APK_FACTORY_API/projects/$APK_FACTORY_PROJECT_ID/signing/keystore" \
      -H 'content-type: application/json' \
      -d "{\"keystoreBase64\":\"$B64\",\"certSha256\":\"$CERT_SHA\"}" >/dev/null \
      || echo ">> [sign] WARNING: could not persist keystore — next build would generate a different key"
  fi
fi

# gradle.properties (values are read by signing.gradle; never echoed)
{
  echo "UPLOAD_STORE_FILE=$KS_PATH"
  echo "UPLOAD_KEY_ALIAS=$ALIAS"
  echo "UPLOAD_STORE_PASSWORD=$UPLOAD_STORE_PASSWORD"
  echo "UPLOAD_KEY_PASSWORD=$UPLOAD_KEY_PASSWORD"
} >> "$ANDROID_DIR/gradle.properties"

# Drop-in signing config. Applied via an init script so user files stay untouched.
cat > "$ANDROID_DIR/apk-factory-signing.gradle" <<'EOF'
// Generated by Cloud APK Factory — release signing from vault-injected credentials.
allprojects {
  afterEvaluate { project ->
    if (project.plugins.hasPlugin('com.android.application')) {
      project.android {
        signingConfigs {
          apkFactoryRelease {
            storeFile project.file(project.findProperty('UPLOAD_STORE_FILE') ?: 'release.keystore')
            storePassword project.findProperty('UPLOAD_STORE_PASSWORD')
            keyAlias project.findProperty('UPLOAD_KEY_ALIAS')
            keyPassword project.findProperty('UPLOAD_KEY_PASSWORD')
          }
        }
        buildTypes.release.signingConfig = signingConfigs.apkFactoryRelease
      }
    }
  }
}
EOF
export GRADLE_OPTS="${GRADLE_OPTS:-} --init-script $(cd "$ANDROID_DIR" && pwd)/apk-factory-signing.gradle"
echo ">> [sign] release signing ready (alias=$ALIAS, keystore=$KS_PATH)"
